CREATE TABLE users(
    id BIGSERIAL PRIMARY KEY,
    login TEXT NOT NULL,
    url TEXT NOT NULL
);

CREATE TABLE roles(
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE users_roles(
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT,
    role_id BIGINT
);

ALTER TABLE users_roles
ADD CONSTRAINT "fk_user" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
ADD CONSTRAINT "fk_role" FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;